### PR TITLE
Repository Upgrades

### PR DESCRIPTION
**Pull request by jakeoid**
Restructured to look more inline with other content inside of whats-th.is.

### CODE REVIEW

**Comment by jakeoid** [comment]
Conflict shouldn't arise, not sure why its saying that it is here. You can probably fix it inside of Desktop and it would be happy. 

Enjoy 👌 !

**Comment by Martmists-GH** [comment]
Seems good, will merge once I get home :ok_hand:

**Comment by aurieh** [comment]
I will rebase & merge if I have the time to (that is, in a few hours), if not, Mart's gonna do it 👀

**Comment by aurieh** [comment]
Resolved & merged, because @martmists is lazy :roll_eyes:

**Comment by Martmists-GH** [comment]
Did you just assume my gender?

**Comment by aurieh** [comment]
~~I can revert and make you resolve the changes yourself :^)~~
no jk

**Pull request merged**
